profile usage fixes for backup

diff --git a/bin/u-backup b/bin/u-backup
--- a/bin/u-backup
+++ b/bin/u-backup
@@ -42,7 +42,7 @@ check_single_required_arg() {
 
 read_config() {
     config="$1"
-    [[ -s $config ]] || err "$config is not a non-empty file"
+    [[ -s $config ]] || err "$config does not exist or empty"
 
     read_config_lines < $config
 }
@@ -62,12 +62,12 @@ read_config_lines() {
 		    err "$cmd argument $dir is not a path relative to \$HOME"
 		backup_paths+=("$dir")
 		;;
-	    
+
 	    PasswordDir )
 		check_single_required_arg
 		password_dir="${args[0]}"
 		;;
-	    
+
 	    BackupTarget )
 		check_single_required_arg
 		backup_targets+=("${args[0]}")
@@ -187,7 +187,6 @@ change_password=
 
 
 while getopts ":fhlP" OPT; do
-
     case "$OPT" in
 	h ) show_usage=1 ;;
 	P ) change_password=1 ;;
@@ -195,21 +194,27 @@ while getopts ":fhlP" OPT; do
     esac
 
 done
+shift $(($OPTIND - 1))
 
 if [[ $show_usage ]]; then
     usage
     exit 0
 fi
 
+[[ $# -ge 1 ]] || err "the profile name argument is missing"
+profile_name="$1"
+shift
+[[ $# -eq 0 ]] || err "unexpected argument after the profile name"
+
 cd "$HOME"
 
-read_config .local/hsetup/backup.config
+read_config ".local/hsetup/$profile_name.backup.config"
 check_config
 
 if [[ $change_password ]]; then
     change_password
     exit 0
 fi
-    
+
 duplicity_create_local_backup
-copy_to_remote 
+copy_to_remote
